apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-of-apps-cursor
  namespace: app-of-apps-cursor
spec:
  project: signal
  source:
    repoURL: https://github.com/draskomikic/app-of-apps-cursor.git
    targetRevision: HEAD
    path: apps
  destination:
    server: https://kubernetes.default.svc
    namespace: app-of-apps-cursor
  syncPolicy:
    automated:
      prune: true
      selfHeal: true 